language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - export APP_SETTINGS="project.server.config.TestingConfig"
  - export SECRET_KEY="justatest"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

before_script:
  - psql -c "CREATE DATABASE python_flask_api_boilerplate_test;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - python manage.py DB init
  - python manage.py DB migrate
  - python manage.py DB upgrade

script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=project/server
  - coveralls
  - codecov --token=d8dafad7-611e-4023-a550-bfa76d8ea38a

after_success:
  - "coveralls"